num1, num2 = map(int, input("Enter two numbers: ").split())
print(num1,"+",num2,"=",num1+num2)
print(num1,"-",num2,"=",num1-num2)
print(num1,"*",num2,"=",num1*num2)
print(num1,"/",num2,"=",num1/num2)
print(num1,"%",num2,"=",num1%num2)
